local syntax = require "core.syntax"

syntax.add {
  files = { "%.asm$", "%.s$", "%.6502$",},
  comment = ";",
  patterns = {
    { pattern = ";.-\n",               type = "comment"  },
    { pattern = { '"', '"', '\\' },     type = "string"   },
    { pattern = { "'", "'", '\\' },     type = "string"   },
    { pattern = "#$[%da-fA-F]+",        type = "number"   },
    { pattern = "$[%da-fA-F]+",        type = "number"   },
    { pattern = "#[%da-fA-F]+",        type = "number"   },
    { pattern = "-?%d+[%d%.eE]*",       type = "number"   },
    { pattern = "-?%.?%d+",             type = "number"   },
    { pattern = "[%+%-=/%*%^%%<>!~|&]", type = "operator" },
    { pattern = "[%a_][%w_]*%f[:]",     type = "function" },
    { pattern = "[%a_][%w_]*",          type = "symbol"   },
  },
  symbols = {
		["ADC"]			= "keyword",
		["AND"]			= "keyword",
		["ASL"]			= "keyword",
		["BCC"]			= "keyword",
		["BCS"]			= "keyword",
		["BEQ"]			= "keyword",
		["BIT"]			= "keyword",
		["BMI"]			= "keyword",
		["BNE"]			= "keyword",

		["BBR0"]		= "keyword",
		["BBR1"]		= "keyword",
		["BBR2"]		= "keyword",
		["BBR3"]		= "keyword",
		["BBR4"]		= "keyword",
		["BBR5"]		= "keyword",
		["BBR6"]		= "keyword",
		["BBR7"]		= "keyword",

		["RMB0"]		= "keyword",
		["RMB1"]		= "keyword",
		["RMB2"]		= "keyword",
		["RMB3"]		= "keyword",
		["RMB4"]		= "keyword",
		["RMB5"]		= "keyword",
		["RMB6"]		= "keyword",
		["RMB7"]		= "keyword",

		["BBS0"]		= "keyword",
		["BBS1"]		= "keyword",
		["BBS2"]		= "keyword",
		["BBS3"]		= "keyword",
		["BBS4"]		= "keyword",
		["BBS4"]		= "keyword",
		["BBS5"]		= "keyword",
		["BBS6"]		= "keyword",
		["BBS7"]		= "keyword",

		["SMB0"]		= "keyword",
		["SMB1"]		= "keyword",
		["SMB2"]		= "keyword",
		["SMB3"]		= "keyword",
		["SMB4"]		= "keyword",
		["SMB5"]		= "keyword",
		["SMB6"]		= "keyword",
		["SMB7"]		= "keyword",

		["BRK"]			= "keyword",
		["BPL"]			= "keyword",
		["BVC"]			= "keyword",
		["BVS"]			= "keyword",
		["CLC"]			= "keyword",
		["CLD"]			= "keyword",
		["CLI"]			= "keyword",
		["CLV"]			= "keyword",
		["CMP"]			= "keyword",
		["CPX"]			= "keyword",
		["CPY"]			= "keyword",
		["DEC"]			= "keyword",
		["DEA"]			= "keyword",
		["DEX"]			= "keyword",
		["DEY"]			= "keyword",
		["EOR"]			= "keyword",
		["INC"]			= "keyword",
		["INA"]			= "keyword",
		["INX"]			= "keyword",
		["INY"]			= "keyword",
		["JMP"]			= "keyword",
		["JSR"]			= "keyword",
		["LDA"]     = "keyword",
    ["LDX"]     = "keyword",
		["LDY"]     = "keyword",
		["LSR"]			= "keyword",
		["NOP"]			= "keyword",
		["ORA"]			= "keyword",
		["PHA"]			= "keyword",
		["PHY"]			= "keyword",
		["PHX"]			= "keyword",
		["PHP"]			= "keyword",
		["PLA"]			= "keyword",
		["PLY"]			= "keyword",
		["PLX"]			= "keyword",
		["PLP"]			= "keyword",
		["ROR"]			= "keyword",
		["ROL"]			= "keyword",
		["RTI"]			= "keyword",
		["RTS"]			= "keyword",
		["SBC"]			= "keyword",
		["SEC"]			= "keyword",
		["SED"]			= "keyword",
		["SEI"]			= "keyword",
    ["STA"]     = "keyword",
    ["STX"]     = "keyword",
		["STY"]     = "keyword",
		["STZ"]     = "keyword",
		["TAX"]     = "keyword",
		["TAY"]     = "keyword",
		["TSX"]     = "keyword",
		["TXA"]     = "keyword",
		["TSB"]     = "keyword",
		["TRB"]     = "keyword",
		["TXS"]     = "keyword",
		["TYA"]     = "keyword",
		["DB"]     = "keyword2",
		["EQU"]     = "keyword2",
		["ORG"]     = "keyword2",
		["END"]     = "keyword2",
		["MACRO"]		= "keyword2",
		["ENDM"]		= "keyword2",
		["BYTE"]		= "keyword2",
		["WORD"]		= "keyword2",
		["INCLUDE"]		= "keyword2",
		["INCBIN"]		= "keyword2",
  },
}
